# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package



on:
  push:
    branches: 
      - Master

jobs:
  build:
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        
    - name: Get Tag
      uses: anothrNick/github-tag-action@1.36.0
      id: getTag
      env: 
        DRY_RUN: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INITIAL_VERSION: 0.0.0
    
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
   # - name: update version
    #  run: mvn --batch-mode release:update-versions -DdevelopmentVersion=${{ steps.getTag.outputs.new_tag }}
     # env:
      #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
        
    - name: Build and publish package
      run: |
        mvn --batch-mode release:update-versions -DdevelopmentVersion=${{ steps.getTag.outputs.new_tag }}
        mvn -B package --file pom.xml
        mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
#    - name: Publish package
 #     run: mvn --batch-mode deploy
  #    env:
   #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create GitHub release
      uses: elgohr/Github-Release-Action@master
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        args: ${{ steps.getTag.outputs.new_tag }}
        
    - name: create a tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
